# Setup
title:               DevOps Rich
tagline:             'DevOps content for Infrastructure Engineers'
description: '<p><img src="/avatar.png" alt="Avatar" style="float: left; margin-right: 15px;" class="avatar">
&nbsp;<h2>Rich</h2>   
&nbsp;<p>Azure DevOps, Terraform, PowerShell, Azure Policy and more.</p><p><a href="https://linkedin.com/in/richardbjhudson" title="Linkedin"><i class="fa fa-linkedin-square"></i></a>
&nbsp;<a href="https://www.twitter.com/devops_rich" title="Twitter"><i class="fa fa-twitter-square"></i></a>
&nbsp;<a href="mailto:richard.b.j.hudson@gmail.com" title="Email"><i class="fa fa-envelope-square"></i></a>
&nbsp;<a href="https://github.com/richbjhudson" title="GitHub"><i class="fa fa-github-square"></i></a></p>'
url:                 "https://devopsrich.com"
baseurl:             ''
paginate:            5
permalink:           pretty
disqus: 'devopsrich'

# About/contact
author:
  name:              Richard Hudson
  url:               https://twitter.com/devops_rich
  email:             richard.b.j.hudson@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

#Collections
collections:
  notes: