# Setup
title:               DevOps Rich
tagline:             'DevOps content for Infrastructure Engineers'
description:         '{% include social-media-links.html %}'
url:                 "https://devopsrich.com"
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Richard Hudson
  url:               https://twitter.com/devops_rich
  email:             richard.b.j.hudson@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
